version: '3'
services:
    pocket-nginx:
        build:
            context: pocket/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./pocket:/app
        depends_on:
            - pocket-php-fpm
        ports:
            - "8080:80"
    pocket-php-fpm:
        build:
            context: pocket/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./pocket:/app
        depends_on:
            - pocket-postgres
    pocket-php-cli:
        build:
            context: pocket/docker/development
            dockerfile: php-cli.docker
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./pocket:/app
            - composer:/root/.composer/cache
        depends_on:
            - pocket-postgres
    pocket-postgres:
        image: postgres:11.2-alpine
        volumes:
            - pocket-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"

volumes:
    pocket-postgres:
    composer: