version: '3'
services:
    pocket-nginx:
        image: ${REGISTRY_ADDRESS}/pocket-nginx:${IMAGE_TAG}
        restart: always
        depends_on:
            - pocket-php-fpm
        ports:
            - "80:80"
    pocket-php-fpm:
        image: ${REGISTRY_ADDRESS}/pocket-php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_SECRET: ${POCKET_APP_SECRET}
            DATABASE_URL: pgsql://app:${POCKET_DB_PASSWORD}@pocket-postgres:5432/app
            MAILER_URL: null://localhost
        depends_on:
            - pocket-postgres
    pocket-php-cli:
        image: ${REGISTRY_ADDRESS}/pocket-php-cli:${IMAGE_TAG}
        environment:
            APP_SECRET: ${POCKET_APP_SECRET}
            DATABASE_URL: pgsql://app:${POCKET_DB_PASSWORD}@pocket-postgres:5432/app
            MAILER_URL: null://localhost
        depends_on:
            - pocket-postgres
    pocket-postgres:
        image: ${REGISTRY_ADDRESS}/pocket-postgres:${IMAGE_TAG}
        restart: always
        volumes:
            - pocket-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${POCKET_DB_PASSWORD}
            POSTGRES_DB: app

volumes:
    pocket-postgres:
