parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: -

        url: '%env(resolve:DATABASE_URL)%'

        types:
            pocket_id: 'App\Model\Pocket\Entity\Pocket\IdType'
            pocket_client_id: 'App\Model\Pocket\Entity\Pocket\ClientIdType'
            pocket_network: 'App\Model\Pocket\Entity\Pocket\NetworkType'
            pocket_pocket_id: 'App\Model\Pocket\Entity\Pocket\PocketIdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Pocket:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Pocket/Entity'
                prefix: 'App\Model\Pocket\Entity'
                alias: Pocket
